// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.0
// source: profile.proto

package profile

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProfileServiceClient is the client API for ProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProfileServiceClient interface {
	// --- профиль жителя ---
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
	UpsertProfile(ctx context.Context, in *UpsertProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
	IsProfileComplete(ctx context.Context, in *IsProfileCompleteRequest, opts ...grpc.CallOption) (*IsProfileCompleteResponse, error)
	// --- управляющие компании (только admin) ---
	CreateManagementCompany(ctx context.Context, in *CreateManagementCompanyRequest, opts ...grpc.CallOption) (*ManagementCompanyResponse, error)
	ListManagementCompanies(ctx context.Context, in *ListManagementCompaniesRequest, opts ...grpc.CallOption) (*ListManagementCompaniesResponse, error)
	// --- дома (только admin) ---
	CreateHouse(ctx context.Context, in *CreateHouseRequest, opts ...grpc.CallOption) (*HouseResponse, error)
	ListHouses(ctx context.Context, in *ListHousesRequest, opts ...grpc.CallOption) (*ListHousesResponse, error)
}

type profileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProfileServiceClient(cc grpc.ClientConnInterface) ProfileServiceClient {
	return &profileServiceClient{cc}
}

func (c *profileServiceClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	out := new(ProfileResponse)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/GetProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) UpsertProfile(ctx context.Context, in *UpsertProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	out := new(ProfileResponse)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/UpsertProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) IsProfileComplete(ctx context.Context, in *IsProfileCompleteRequest, opts ...grpc.CallOption) (*IsProfileCompleteResponse, error) {
	out := new(IsProfileCompleteResponse)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/IsProfileComplete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) CreateManagementCompany(ctx context.Context, in *CreateManagementCompanyRequest, opts ...grpc.CallOption) (*ManagementCompanyResponse, error) {
	out := new(ManagementCompanyResponse)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/CreateManagementCompany", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) ListManagementCompanies(ctx context.Context, in *ListManagementCompaniesRequest, opts ...grpc.CallOption) (*ListManagementCompaniesResponse, error) {
	out := new(ListManagementCompaniesResponse)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/ListManagementCompanies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) CreateHouse(ctx context.Context, in *CreateHouseRequest, opts ...grpc.CallOption) (*HouseResponse, error) {
	out := new(HouseResponse)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/CreateHouse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) ListHouses(ctx context.Context, in *ListHousesRequest, opts ...grpc.CallOption) (*ListHousesResponse, error) {
	out := new(ListHousesResponse)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/ListHouses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileServiceServer is the server API for ProfileService service.
// All implementations should embed UnimplementedProfileServiceServer
// for forward compatibility
type ProfileServiceServer interface {
	// --- профиль жителя ---
	GetProfile(context.Context, *GetProfileRequest) (*ProfileResponse, error)
	UpsertProfile(context.Context, *UpsertProfileRequest) (*ProfileResponse, error)
	IsProfileComplete(context.Context, *IsProfileCompleteRequest) (*IsProfileCompleteResponse, error)
	// --- управляющие компании (только admin) ---
	CreateManagementCompany(context.Context, *CreateManagementCompanyRequest) (*ManagementCompanyResponse, error)
	ListManagementCompanies(context.Context, *ListManagementCompaniesRequest) (*ListManagementCompaniesResponse, error)
	// --- дома (только admin) ---
	CreateHouse(context.Context, *CreateHouseRequest) (*HouseResponse, error)
	ListHouses(context.Context, *ListHousesRequest) (*ListHousesResponse, error)
}

// UnimplementedProfileServiceServer should be embedded to have forward compatible implementations.
type UnimplementedProfileServiceServer struct {
}

func (UnimplementedProfileServiceServer) GetProfile(context.Context, *GetProfileRequest) (*ProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedProfileServiceServer) UpsertProfile(context.Context, *UpsertProfileRequest) (*ProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertProfile not implemented")
}
func (UnimplementedProfileServiceServer) IsProfileComplete(context.Context, *IsProfileCompleteRequest) (*IsProfileCompleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsProfileComplete not implemented")
}
func (UnimplementedProfileServiceServer) CreateManagementCompany(context.Context, *CreateManagementCompanyRequest) (*ManagementCompanyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateManagementCompany not implemented")
}
func (UnimplementedProfileServiceServer) ListManagementCompanies(context.Context, *ListManagementCompaniesRequest) (*ListManagementCompaniesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListManagementCompanies not implemented")
}
func (UnimplementedProfileServiceServer) CreateHouse(context.Context, *CreateHouseRequest) (*HouseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHouse not implemented")
}
func (UnimplementedProfileServiceServer) ListHouses(context.Context, *ListHousesRequest) (*ListHousesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHouses not implemented")
}

// UnsafeProfileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProfileServiceServer will
// result in compilation errors.
type UnsafeProfileServiceServer interface {
	mustEmbedUnimplementedProfileServiceServer()
}

func RegisterProfileServiceServer(s grpc.ServiceRegistrar, srv ProfileServiceServer) {
	s.RegisterService(&ProfileService_ServiceDesc, srv)
}

func _ProfileService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/GetProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_UpsertProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).UpsertProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/UpsertProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).UpsertProfile(ctx, req.(*UpsertProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_IsProfileComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsProfileCompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).IsProfileComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/IsProfileComplete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).IsProfileComplete(ctx, req.(*IsProfileCompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_CreateManagementCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateManagementCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).CreateManagementCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/CreateManagementCompany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).CreateManagementCompany(ctx, req.(*CreateManagementCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_ListManagementCompanies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListManagementCompaniesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).ListManagementCompanies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/ListManagementCompanies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).ListManagementCompanies(ctx, req.(*ListManagementCompaniesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_CreateHouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHouseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).CreateHouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/CreateHouse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).CreateHouse(ctx, req.(*CreateHouseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_ListHouses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHousesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).ListHouses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/ListHouses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).ListHouses(ctx, req.(*ListHousesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProfileService_ServiceDesc is the grpc.ServiceDesc for ProfileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProfileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "profile.ProfileService",
	HandlerType: (*ProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProfile",
			Handler:    _ProfileService_GetProfile_Handler,
		},
		{
			MethodName: "UpsertProfile",
			Handler:    _ProfileService_UpsertProfile_Handler,
		},
		{
			MethodName: "IsProfileComplete",
			Handler:    _ProfileService_IsProfileComplete_Handler,
		},
		{
			MethodName: "CreateManagementCompany",
			Handler:    _ProfileService_CreateManagementCompany_Handler,
		},
		{
			MethodName: "ListManagementCompanies",
			Handler:    _ProfileService_ListManagementCompanies_Handler,
		},
		{
			MethodName: "CreateHouse",
			Handler:    _ProfileService_CreateHouse_Handler,
		},
		{
			MethodName: "ListHouses",
			Handler:    _ProfileService_ListHouses_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "profile.proto",
}
