version: "2"
run:
  tests: false
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - forbidigo
    - forcetypeassert
    - gochecknoinits
    - goconst
    - gocritic
    - godox
    - gosec
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - nlreturn
    - noctx
    - nonamedreturns
    - paralleltest
    - prealloc
    - promlinter
    - protogetter
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - testpackage
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
    - wsl_v5
    - zerologlint
  settings:
    cyclop:
      max-complexity: 20
    decorder:
      dec-order:
        - const
        - var
        - type
        - func
    lll:
      line-length: 150
  exclusions:
    generated: lax
    rules:
      - linters:
          - gosec
        text: "G101|G117"
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(profile-service)
      custom-order: true
    gofumpt:
      module-path: profile-service
    goimports:
      local-prefixes:
        - profile-service
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - tmp$
      - testing$
