// Code generated by MockGen. DO NOT EDIT.
// Source: services/requests/interfaces.go

// Package requests_service is a generated GoMock package.
package requests_service

import (
	context "context"
	reflect "reflect"
	domain "requests-service/infra/models/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddComment mocks base method.
func (m *MockRepository) AddComment(ctx context.Context, comment *domain.Comment) (*domain.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddComment", ctx, comment)
	ret0, _ := ret[0].(*domain.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddComment indicates an expected call of AddComment.
func (mr *MockRepositoryMockRecorder) AddComment(ctx, comment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddComment", reflect.TypeOf((*MockRepository)(nil).AddComment), ctx, comment)
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, req *domain.MaintenanceRequest) (*domain.MaintenanceRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*domain.MaintenanceRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, req)
}

// GetByID mocks base method.
func (m *MockRepository) GetByID(ctx context.Context, id string) (*domain.MaintenanceRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.MaintenanceRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockRepository) List(ctx context.Context, req *domain.GetRequestsRequest) ([]*domain.MaintenanceRequest, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, req)
	ret0, _ := ret[0].([]*domain.MaintenanceRequest)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockRepositoryMockRecorder) List(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository)(nil).List), ctx, req)
}

// ListComments mocks base method.
func (m *MockRepository) ListComments(ctx context.Context, requestID string) ([]*domain.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListComments", ctx, requestID)
	ret0, _ := ret[0].([]*domain.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListComments indicates an expected call of ListComments.
func (mr *MockRepositoryMockRecorder) ListComments(ctx, requestID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListComments", reflect.TypeOf((*MockRepository)(nil).ListComments), ctx, requestID)
}

// UpdateStatus mocks base method.
func (m *MockRepository) UpdateStatus(ctx context.Context, id, status string) (*domain.MaintenanceRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(*domain.MaintenanceRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockRepositoryMockRecorder) UpdateStatus(ctx, id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockRepository)(nil).UpdateStatus), ctx, id, status)
}

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// PublishRequestCommentAdded mocks base method.
func (m *MockPublisher) PublishRequestCommentAdded(ctx context.Context, evt domain.RequestEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishRequestCommentAdded", ctx, evt)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishRequestCommentAdded indicates an expected call of PublishRequestCommentAdded.
func (mr *MockPublisherMockRecorder) PublishRequestCommentAdded(ctx, evt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishRequestCommentAdded", reflect.TypeOf((*MockPublisher)(nil).PublishRequestCommentAdded), ctx, evt)
}

// PublishRequestCreated mocks base method.
func (m *MockPublisher) PublishRequestCreated(ctx context.Context, evt domain.RequestEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishRequestCreated", ctx, evt)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishRequestCreated indicates an expected call of PublishRequestCreated.
func (mr *MockPublisherMockRecorder) PublishRequestCreated(ctx, evt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishRequestCreated", reflect.TypeOf((*MockPublisher)(nil).PublishRequestCreated), ctx, evt)
}

// PublishRequestStatusUpdated mocks base method.
func (m *MockPublisher) PublishRequestStatusUpdated(ctx context.Context, evt domain.RequestEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishRequestStatusUpdated", ctx, evt)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishRequestStatusUpdated indicates an expected call of PublishRequestStatusUpdated.
func (mr *MockPublisherMockRecorder) PublishRequestStatusUpdated(ctx, evt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishRequestStatusUpdated", reflect.TypeOf((*MockPublisher)(nil).PublishRequestStatusUpdated), ctx, evt)
}
