// Code generated by MockGen. DO NOT EDIT.
// Source: infra/mq/publisher.go

// Package mq is a generated GoMock package.
package mq

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	amqp091 "github.com/rabbitmq/amqp091-go"
)

// MockpublisherChannel is a mock of publisherChannel interface.
type MockpublisherChannel struct {
	ctrl     *gomock.Controller
	recorder *MockpublisherChannelMockRecorder
}

// MockpublisherChannelMockRecorder is the mock recorder for MockpublisherChannel.
type MockpublisherChannelMockRecorder struct {
	mock *MockpublisherChannel
}

// NewMockpublisherChannel creates a new mock instance.
func NewMockpublisherChannel(ctrl *gomock.Controller) *MockpublisherChannel {
	mock := &MockpublisherChannel{ctrl: ctrl}
	mock.recorder = &MockpublisherChannelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpublisherChannel) EXPECT() *MockpublisherChannelMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockpublisherChannel) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockpublisherChannelMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockpublisherChannel)(nil).Close))
}

// PublishWithContext mocks base method.
func (m *MockpublisherChannel) PublishWithContext(arg0 context.Context, arg1, arg2 string, arg3, arg4 bool, arg5 amqp091.Publishing) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishWithContext", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishWithContext indicates an expected call of PublishWithContext.
func (mr *MockpublisherChannelMockRecorder) PublishWithContext(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishWithContext", reflect.TypeOf((*MockpublisherChannel)(nil).PublishWithContext), arg0, arg1, arg2, arg3, arg4, arg5)
}
