// Code generated by MockGen. DO NOT EDIT.
// Source: services/profile/interfaces.go

// Package profile_service is a generated GoMock package.
package profile_service

import (
	context "context"
	domain "profile-service/infra/models/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateHouse mocks base method.
func (m *MockRepository) CreateHouse(ctx context.Context, house *domain.House) (*domain.House, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateHouse", ctx, house)
	ret0, _ := ret[0].(*domain.House)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateHouse indicates an expected call of CreateHouse.
func (mr *MockRepositoryMockRecorder) CreateHouse(ctx, house interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateHouse", reflect.TypeOf((*MockRepository)(nil).CreateHouse), ctx, house)
}

// CreateManagementCompany mocks base method.
func (m *MockRepository) CreateManagementCompany(ctx context.Context, company *domain.ManagementCompany) (*domain.ManagementCompany, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateManagementCompany", ctx, company)
	ret0, _ := ret[0].(*domain.ManagementCompany)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateManagementCompany indicates an expected call of CreateManagementCompany.
func (mr *MockRepositoryMockRecorder) CreateManagementCompany(ctx, company interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateManagementCompany", reflect.TypeOf((*MockRepository)(nil).CreateManagementCompany), ctx, company)
}

// GetProfile mocks base method.
func (m *MockRepository) GetProfile(ctx context.Context, userID string) (*domain.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", ctx, userID)
	ret0, _ := ret[0].(*domain.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockRepositoryMockRecorder) GetProfile(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockRepository)(nil).GetProfile), ctx, userID)
}

// IsProfileComplete mocks base method.
func (m *MockRepository) IsProfileComplete(ctx context.Context, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsProfileComplete", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsProfileComplete indicates an expected call of IsProfileComplete.
func (mr *MockRepositoryMockRecorder) IsProfileComplete(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsProfileComplete", reflect.TypeOf((*MockRepository)(nil).IsProfileComplete), ctx, userID)
}

// ListHouses mocks base method.
func (m *MockRepository) ListHouses(ctx context.Context, ukID string) ([]*domain.House, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHouses", ctx, ukID)
	ret0, _ := ret[0].([]*domain.House)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListHouses indicates an expected call of ListHouses.
func (mr *MockRepositoryMockRecorder) ListHouses(ctx, ukID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHouses", reflect.TypeOf((*MockRepository)(nil).ListHouses), ctx, ukID)
}

// ListManagementCompanies mocks base method.
func (m *MockRepository) ListManagementCompanies(ctx context.Context) ([]*domain.ManagementCompany, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListManagementCompanies", ctx)
	ret0, _ := ret[0].([]*domain.ManagementCompany)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListManagementCompanies indicates an expected call of ListManagementCompanies.
func (mr *MockRepositoryMockRecorder) ListManagementCompanies(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListManagementCompanies", reflect.TypeOf((*MockRepository)(nil).ListManagementCompanies), ctx)
}

// UpsertProfile mocks base method.
func (m *MockRepository) UpsertProfile(ctx context.Context, profile *domain.Profile) (*domain.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertProfile", ctx, profile)
	ret0, _ := ret[0].(*domain.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertProfile indicates an expected call of UpsertProfile.
func (mr *MockRepositoryMockRecorder) UpsertProfile(ctx, profile interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertProfile", reflect.TypeOf((*MockRepository)(nil).UpsertProfile), ctx, profile)
}
