// Code generated by MockGen. DO NOT EDIT.
// Source: api/server/interfaces.go

// Package server is a generated GoMock package.
package server

import (
	context "context"
	domain "news-service/infra/models/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockNewsService is a mock of NewsService interface.
type MockNewsService struct {
	ctrl     *gomock.Controller
	recorder *MockNewsServiceMockRecorder
}

// MockNewsServiceMockRecorder is the mock recorder for MockNewsService.
type MockNewsServiceMockRecorder struct {
	mock *MockNewsService
}

// NewMockNewsService creates a new mock instance.
func NewMockNewsService(ctrl *gomock.Controller) *MockNewsService {
	mock := &MockNewsService{ctrl: ctrl}
	mock.recorder = &MockNewsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNewsService) EXPECT() *MockNewsServiceMockRecorder {
	return m.recorder
}

// CreateNews mocks base method.
func (m *MockNewsService) CreateNews(ctx context.Context, req *domain.CreateNewsRequest) (*domain.News, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNews", ctx, req)
	ret0, _ := ret[0].(*domain.News)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNews indicates an expected call of CreateNews.
func (mr *MockNewsServiceMockRecorder) CreateNews(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNews", reflect.TypeOf((*MockNewsService)(nil).CreateNews), ctx, req)
}

// GetNews mocks base method.
func (m *MockNewsService) GetNews(ctx context.Context, req *domain.GetNewsRequest) ([]*domain.News, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNews", ctx, req)
	ret0, _ := ret[0].([]*domain.News)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetNews indicates an expected call of GetNews.
func (mr *MockNewsServiceMockRecorder) GetNews(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNews", reflect.TypeOf((*MockNewsService)(nil).GetNews), ctx, req)
}

// GetNewsItem mocks base method.
func (m *MockNewsService) GetNewsItem(ctx context.Context, id string) (*domain.News, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNewsItem", ctx, id)
	ret0, _ := ret[0].(*domain.News)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNewsItem indicates an expected call of GetNewsItem.
func (mr *MockNewsServiceMockRecorder) GetNewsItem(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNewsItem", reflect.TypeOf((*MockNewsService)(nil).GetNewsItem), ctx, id)
}
