// Code generated by MockGen. DO NOT EDIT.
// Source: api/server/interfaces.go

// Package server is a generated GoMock package.
package server

import (
	context "context"
	reflect "reflect"
	domain "requests-service/infra/models/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockRequestsService is a mock of RequestsService interface.
type MockRequestsService struct {
	ctrl     *gomock.Controller
	recorder *MockRequestsServiceMockRecorder
}

// MockRequestsServiceMockRecorder is the mock recorder for MockRequestsService.
type MockRequestsServiceMockRecorder struct {
	mock *MockRequestsService
}

// NewMockRequestsService creates a new mock instance.
func NewMockRequestsService(ctrl *gomock.Controller) *MockRequestsService {
	mock := &MockRequestsService{ctrl: ctrl}
	mock.recorder = &MockRequestsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestsService) EXPECT() *MockRequestsServiceMockRecorder {
	return m.recorder
}

// AddComment mocks base method.
func (m *MockRequestsService) AddComment(ctx context.Context, req *domain.AddCommentRequest) (*domain.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddComment", ctx, req)
	ret0, _ := ret[0].(*domain.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddComment indicates an expected call of AddComment.
func (mr *MockRequestsServiceMockRecorder) AddComment(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddComment", reflect.TypeOf((*MockRequestsService)(nil).AddComment), ctx, req)
}

// CreateRequest mocks base method.
func (m *MockRequestsService) CreateRequest(ctx context.Context, req *domain.CreateRequestRequest) (*domain.MaintenanceRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRequest", ctx, req)
	ret0, _ := ret[0].(*domain.MaintenanceRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRequest indicates an expected call of CreateRequest.
func (mr *MockRequestsServiceMockRecorder) CreateRequest(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRequest", reflect.TypeOf((*MockRequestsService)(nil).CreateRequest), ctx, req)
}

// GetComments mocks base method.
func (m *MockRequestsService) GetComments(ctx context.Context, requestID string) ([]*domain.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComments", ctx, requestID)
	ret0, _ := ret[0].([]*domain.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComments indicates an expected call of GetComments.
func (mr *MockRequestsServiceMockRecorder) GetComments(ctx, requestID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComments", reflect.TypeOf((*MockRequestsService)(nil).GetComments), ctx, requestID)
}

// GetRequest mocks base method.
func (m *MockRequestsService) GetRequest(ctx context.Context, id string) (*domain.MaintenanceRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequest", ctx, id)
	ret0, _ := ret[0].(*domain.MaintenanceRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRequest indicates an expected call of GetRequest.
func (mr *MockRequestsServiceMockRecorder) GetRequest(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequest", reflect.TypeOf((*MockRequestsService)(nil).GetRequest), ctx, id)
}

// GetRequests mocks base method.
func (m *MockRequestsService) GetRequests(ctx context.Context, req *domain.GetRequestsRequest) ([]*domain.MaintenanceRequest, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequests", ctx, req)
	ret0, _ := ret[0].([]*domain.MaintenanceRequest)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRequests indicates an expected call of GetRequests.
func (mr *MockRequestsServiceMockRecorder) GetRequests(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequests", reflect.TypeOf((*MockRequestsService)(nil).GetRequests), ctx, req)
}

// UpdateRequestStatus mocks base method.
func (m *MockRequestsService) UpdateRequestStatus(ctx context.Context, req *domain.UpdateStatusRequest) (*domain.MaintenanceRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRequestStatus", ctx, req)
	ret0, _ := ret[0].(*domain.MaintenanceRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRequestStatus indicates an expected call of UpdateRequestStatus.
func (mr *MockRequestsServiceMockRecorder) UpdateRequestStatus(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRequestStatus", reflect.TypeOf((*MockRequestsService)(nil).UpdateRequestStatus), ctx, req)
}
