// Code generated by MockGen. DO NOT EDIT.
// Source: api/server/interfaces.go

// Package server is a generated GoMock package.
package server

import (
	context "context"
	domain "profile-service/infra/models/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockProfileService is a mock of ProfileService interface.
type MockProfileService struct {
	ctrl     *gomock.Controller
	recorder *MockProfileServiceMockRecorder
}

// MockProfileServiceMockRecorder is the mock recorder for MockProfileService.
type MockProfileServiceMockRecorder struct {
	mock *MockProfileService
}

// NewMockProfileService creates a new mock instance.
func NewMockProfileService(ctrl *gomock.Controller) *MockProfileService {
	mock := &MockProfileService{ctrl: ctrl}
	mock.recorder = &MockProfileServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileService) EXPECT() *MockProfileServiceMockRecorder {
	return m.recorder
}

// CreateHouse mocks base method.
func (m *MockProfileService) CreateHouse(ctx context.Context, req *domain.CreateHouseRequest) (*domain.House, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateHouse", ctx, req)
	ret0, _ := ret[0].(*domain.House)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateHouse indicates an expected call of CreateHouse.
func (mr *MockProfileServiceMockRecorder) CreateHouse(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateHouse", reflect.TypeOf((*MockProfileService)(nil).CreateHouse), ctx, req)
}

// CreateManagementCompany mocks base method.
func (m *MockProfileService) CreateManagementCompany(ctx context.Context, req *domain.CreateManagementCompanyRequest) (*domain.ManagementCompany, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateManagementCompany", ctx, req)
	ret0, _ := ret[0].(*domain.ManagementCompany)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateManagementCompany indicates an expected call of CreateManagementCompany.
func (mr *MockProfileServiceMockRecorder) CreateManagementCompany(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateManagementCompany", reflect.TypeOf((*MockProfileService)(nil).CreateManagementCompany), ctx, req)
}

// GetProfile mocks base method.
func (m *MockProfileService) GetProfile(ctx context.Context, userID string) (*domain.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", ctx, userID)
	ret0, _ := ret[0].(*domain.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockProfileServiceMockRecorder) GetProfile(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockProfileService)(nil).GetProfile), ctx, userID)
}

// IsProfileComplete mocks base method.
func (m *MockProfileService) IsProfileComplete(ctx context.Context, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsProfileComplete", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsProfileComplete indicates an expected call of IsProfileComplete.
func (mr *MockProfileServiceMockRecorder) IsProfileComplete(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsProfileComplete", reflect.TypeOf((*MockProfileService)(nil).IsProfileComplete), ctx, userID)
}

// ListHouses mocks base method.
func (m *MockProfileService) ListHouses(ctx context.Context, req *domain.ListHousesRequest) ([]*domain.House, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHouses", ctx, req)
	ret0, _ := ret[0].([]*domain.House)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListHouses indicates an expected call of ListHouses.
func (mr *MockProfileServiceMockRecorder) ListHouses(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHouses", reflect.TypeOf((*MockProfileService)(nil).ListHouses), ctx, req)
}

// ListManagementCompanies mocks base method.
func (m *MockProfileService) ListManagementCompanies(ctx context.Context) ([]*domain.ManagementCompany, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListManagementCompanies", ctx)
	ret0, _ := ret[0].([]*domain.ManagementCompany)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListManagementCompanies indicates an expected call of ListManagementCompanies.
func (mr *MockProfileServiceMockRecorder) ListManagementCompanies(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListManagementCompanies", reflect.TypeOf((*MockProfileService)(nil).ListManagementCompanies), ctx)
}

// UpsertProfile mocks base method.
func (m *MockProfileService) UpsertProfile(ctx context.Context, req *domain.UpsertProfileRequest) (*domain.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertProfile", ctx, req)
	ret0, _ := ret[0].(*domain.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertProfile indicates an expected call of UpsertProfile.
func (mr *MockProfileServiceMockRecorder) UpsertProfile(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertProfile", reflect.TypeOf((*MockProfileService)(nil).UpsertProfile), ctx, req)
}
